//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradePath.Cli.Resources {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Commands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TradePath.Cli.Resources.Commands", typeof(Commands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database operations - most of the time you don&apos;t need to worry about this.
        /// </summary>
        internal static string Database_Description {
            get {
                return ResourceManager.GetString("Database.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate the database to the latest version.
        /// </summary>
        internal static string Database_Migrate_Description {
            get {
                return ResourceManager.GetString("Database.Migrate.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to migrate.
        /// </summary>
        internal static string Database_Migrate_Name {
            get {
                return ResourceManager.GetString("Database.Migrate.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instead of migrating to the latest version, migrate to a specific version.
        /// </summary>
        internal static string Database_Migrate_Options_Target_Description {
            get {
                return ResourceManager.GetString("Database.Migrate.Options.Target.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -t|--target.
        /// </summary>
        internal static string Database_Migrate_Options_Target_Name {
            get {
                return ResourceManager.GetString("Database.Migrate.Options.Target.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to database.
        /// </summary>
        internal static string Database_Name {
            get {
                return ResourceManager.GetString("Database.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working directory for the command. This is where the database will be created and where supporting files will be processed..
        /// </summary>
        internal static string Global_Directory_Description {
            get {
                return ResourceManager.GetString("Global.Directory.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -d|--directory.
        /// </summary>
        internal static string Global_Directory_Name {
            get {
                return ResourceManager.GetString("Global.Directory.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the verbosity level of the command..
        /// </summary>
        internal static string Global_Verbosity_Description {
            get {
                return ResourceManager.GetString("Global.Verbosity.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -v|--verbosity.
        /// </summary>
        internal static string Global_Verbosity_Name {
            get {
                return ResourceManager.GetString("Global.Verbosity.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin operations.
        /// </summary>
        internal static string Plugin_Description {
            get {
                return ResourceManager.GetString("Plugin.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install a plugin.
        /// </summary>
        internal static string Plugin_Install_Description {
            get {
                return ResourceManager.GetString("Plugin.Install.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to install.
        /// </summary>
        internal static string Plugin_Install_Name {
            get {
                return ResourceManager.GetString("Plugin.Install.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List install plugins.
        /// </summary>
        internal static string Plugin_List_Description {
            get {
                return ResourceManager.GetString("Plugin.List.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing plugin manifests.
        /// </summary>
        internal static string Plugin_List_Messages_ReadingManifests {
            get {
                return ResourceManager.GetString("Plugin.List.Messages.ReadingManifests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning plugin directory.
        /// </summary>
        internal static string Plugin_List_Messages_ScanningInstallation {
            get {
                return ResourceManager.GetString("Plugin.List.Messages.ScanningInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        internal static string Plugin_List_Name {
            get {
                return ResourceManager.GetString("Plugin.List.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugins installed.
        /// </summary>
        internal static string Plugin_Messages_NoPluginsInstalled {
            get {
                return ResourceManager.GetString("Plugin.Messages.NoPluginsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugin.
        /// </summary>
        internal static string Plugin_Name {
            get {
                return ResourceManager.GetString("Plugin.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search plugin sources.
        /// </summary>
        internal static string Plugin_Search_Description {
            get {
                return ResourceManager.GetString("Plugin.Search.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        internal static string Plugin_Search_Name {
            get {
                return ResourceManager.GetString("Plugin.Search.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall a plugin.
        /// </summary>
        internal static string Plugin_Uninstall_Description {
            get {
                return ResourceManager.GetString("Plugin.Uninstall.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uninstall.
        /// </summary>
        internal static string Plugin_Uninstall_Name {
            get {
                return ResourceManager.GetString("Plugin.Uninstall.Name", resourceCulture);
            }
        }
    }
}
