//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradePath.Cli.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Commands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TradePath.Cli.Resources.Commands", typeof(Commands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read and Modify configuration options.
        /// </summary>
        internal static string Configuration_Description {
            get {
                return ResourceManager.GetString("Configuration.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump all configuration values as JSON.
        /// </summary>
        internal static string Configuration_Dump_Description {
            get {
                return ResourceManager.GetString("Configuration.Dump.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dump.
        /// </summary>
        internal static string Configuration_Dump_Name {
            get {
                return ResourceManager.GetString("Configuration.Dump.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Key.
        /// </summary>
        internal static string Configuration_List_Column_Key {
            get {
                return ResourceManager.GetString("Configuration.List.Column.Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Sourced From.
        /// </summary>
        internal static string Configuration_List_Column_Source {
            get {
                return ResourceManager.GetString("Configuration.List.Column.Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Value.
        /// </summary>
        internal static string Configuration_List_Column_Value {
            get {
                return ResourceManager.GetString("Configuration.List.Column.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all configuration values.
        /// </summary>
        internal static string Configuration_List_Description {
            get {
                return ResourceManager.GetString("Configuration.List.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        internal static string Configuration_List_Name {
            get {
                return ResourceManager.GetString("Configuration.List.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.
        /// </summary>
        internal static string Configuration_Name {
            get {
                return ResourceManager.GetString("Configuration.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        internal static string Configuration_Sources_AppSettings {
            get {
                return ResourceManager.GetString("Configuration.Sources.AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-In.
        /// </summary>
        internal static string Configuration_Sources_BuiltIn {
            get {
                return ResourceManager.GetString("Configuration.Sources.BuiltIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Configuration_Sources_Unknown {
            get {
                return ResourceManager.GetString("Configuration.Sources.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database operations - most of the time you don&apos;t need to worry about this.
        /// </summary>
        internal static string Database_Description {
            get {
                return ResourceManager.GetString("Database.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate the database to the latest version.
        /// </summary>
        internal static string Database_Migrate_Description {
            get {
                return ResourceManager.GetString("Database.Migrate.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to migrate.
        /// </summary>
        internal static string Database_Migrate_Name {
            get {
                return ResourceManager.GetString("Database.Migrate.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instead of migrating to the latest version, migrate to a specific version.
        /// </summary>
        internal static string Database_Migrate_Options_Target_Description {
            get {
                return ResourceManager.GetString("Database.Migrate.Options.Target.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -t|--target.
        /// </summary>
        internal static string Database_Migrate_Options_Target_Name {
            get {
                return ResourceManager.GetString("Database.Migrate.Options.Target.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to database.
        /// </summary>
        internal static string Database_Name {
            get {
                return ResourceManager.GetString("Database.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working directory for the command. This is where the database will be created and where supporting files will be processed..
        /// </summary>
        internal static string Global_Directory_Description {
            get {
                return ResourceManager.GetString("Global.Directory.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -d|--directory.
        /// </summary>
        internal static string Global_Directory_Name {
            get {
                return ResourceManager.GetString("Global.Directory.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the verbosity level of the command..
        /// </summary>
        internal static string Global_Verbosity_Description {
            get {
                return ResourceManager.GetString("Global.Verbosity.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -v|--verbosity.
        /// </summary>
        internal static string Global_Verbosity_Name {
            get {
                return ResourceManager.GetString("Global.Verbosity.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin operations.
        /// </summary>
        internal static string Plugin_Description {
            get {
                return ResourceManager.GetString("Plugin.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of the plugin.
        /// </summary>
        internal static string Plugin_Install_Arguments_Id_Description {
            get {
                return ResourceManager.GetString("Plugin.Install.Arguments.Id.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string Plugin_Install_Arguments_Id_Name {
            get {
                return ResourceManager.GetString("Plugin.Install.Arguments.Id.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install a plugin.
        /// </summary>
        internal static string Plugin_Install_Description {
            get {
                return ResourceManager.GetString("Plugin.Install.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing plugin.
        /// </summary>
        internal static string Plugin_Install_Messages_InstallingPlugin {
            get {
                return ResourceManager.GetString("Plugin.Install.Messages.InstallingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse argument &apos;{0}&apos; as a valid NuGet version range..
        /// </summary>
        internal static string Plugin_Install_Messages_InvalidVersionRange {
            get {
                return ResourceManager.GetString("Plugin.Install.Messages.InvalidVersionRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving plugin dependency tree.
        /// </summary>
        internal static string Plugin_Install_Messages_ResolvingDependencies {
            get {
                return ResourceManager.GetString("Plugin.Install.Messages.ResolvingDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducing plugin dependency tree.
        /// </summary>
        internal static string Plugin_Install_Messages_SimplifyingDependencies {
            get {
                return ResourceManager.GetString("Plugin.Install.Messages.SimplifyingDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to install.
        /// </summary>
        internal static string Plugin_Install_Name {
            get {
                return ResourceManager.GetString("Plugin.Install.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the use of pre-release versions.
        /// </summary>
        internal static string Plugin_Install_Options_PreRelease_Description {
            get {
                return ResourceManager.GetString("Plugin.Install.Options.PreRelease.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --pre|--prerelease.
        /// </summary>
        internal static string Plugin_Install_Options_PreRelease_Name {
            get {
                return ResourceManager.GetString("Plugin.Install.Options.PreRelease.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin version, if not specified, defaults to the latest version.
        /// </summary>
        internal static string Plugin_Install_Options_Version_Description {
            get {
                return ResourceManager.GetString("Plugin.Install.Options.Version.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --version.
        /// </summary>
        internal static string Plugin_Install_Options_Version_Name {
            get {
                return ResourceManager.GetString("Plugin.Install.Options.Version.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List install plugins.
        /// </summary>
        internal static string Plugin_List_Description {
            get {
                return ResourceManager.GetString("Plugin.List.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing plugin manifests.
        /// </summary>
        internal static string Plugin_List_Messages_ReadingManifests {
            get {
                return ResourceManager.GetString("Plugin.List.Messages.ReadingManifests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning plugin directory.
        /// </summary>
        internal static string Plugin_List_Messages_ScanningInstallation {
            get {
                return ResourceManager.GetString("Plugin.List.Messages.ScanningInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        internal static string Plugin_List_Name {
            get {
                return ResourceManager.GetString("Plugin.List.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugins installed.
        /// </summary>
        internal static string Plugin_Messages_NoPluginsInstalled {
            get {
                return ResourceManager.GetString("Plugin.Messages.NoPluginsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugin.
        /// </summary>
        internal static string Plugin_Name {
            get {
                return ResourceManager.GetString("Plugin.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search plugin sources.
        /// </summary>
        internal static string Plugin_Search_Description {
            get {
                return ResourceManager.GetString("Plugin.Search.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        internal static string Plugin_Search_Name {
            get {
                return ResourceManager.GetString("Plugin.Search.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall a plugin.
        /// </summary>
        internal static string Plugin_Uninstall_Description {
            get {
                return ResourceManager.GetString("Plugin.Uninstall.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uninstall.
        /// </summary>
        internal static string Plugin_Uninstall_Name {
            get {
                return ResourceManager.GetString("Plugin.Uninstall.Name", resourceCulture);
            }
        }
    }
}
