// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TradePath.DataStore.Database.CompiledModel
{
    public partial class GalDataContextModel
    {
        private GalDataContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("a251725b-0845-48a0-ba64-b37b63a6a8c7"), entityTypeCount: 5)
        {
        }

        partial void Initialize()
        {
            var nameFts = NameFtsEntityType.Create(this);
            var nameFts0 = NameFts0EntityType.Create(this);
            var star = StarEntityType.Create(this);
            var starSystem = StarSystemEntityType.Create(this);
            var station = StationEntityType.Create(this);

            NameFtsEntityType.CreateForeignKey1(nameFts, starSystem);
            NameFts0EntityType.CreateForeignKey1(nameFts0, station);
            StarEntityType.CreateForeignKey1(star, starSystem);
            StationEntityType.CreateForeignKey1(station, starSystem);

            NameFtsEntityType.CreateAnnotations(nameFts);
            NameFts0EntityType.CreateAnnotations(nameFts0);
            StarEntityType.CreateAnnotations(star);
            StarSystemEntityType.CreateAnnotations(starSystem);
            StationEntityType.CreateAnnotations(station);

            AddAnnotation("ProductVersion", "9.0.4");
        }
    }
}
