// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using TradePath.DataStore.Database;
using TradePath.DataStore.Database.CompiledModel;
using TradePath.DataStore.Database;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(GalDataContext), typeof(GalDataContextModel))]
