// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using TradePath.Models;
using TradePath.DataStore.Database;
using Station = TradePath.Models.Station;
using StationId = TradePath.Models.StationId;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TradePath.DataStore.Database.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class NameFts0EntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "TradePath.DataStore.Database.NameFts<TradePath.Models.StationId, TradePath.Models.Station>",
                typeof(NameFts<StationId, Station>),
                baseEntityType,
                propertyCount: 4,
                navigationCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(StationId),
                propertyInfo: typeof(NameFts<StationId, Station>).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NameFts<StationId, Station>).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueConverter: new TradePath.DataStore.Database.EfCoreVogenConverters.StationIdEfCoreValueConverter(),
                valueComparer: new TradePath.DataStore.Database.EfCoreVogenConverters.StationIdEfCoreValueComparer());

            var entityId = runtimeEntityType.AddProperty(
                "EntityId",
                typeof(StationId),
                propertyInfo: typeof(NameFts<StationId, Station>).GetProperty("EntityId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NameFts<StationId, Station>).GetField("<EntityId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new TradePath.DataStore.Database.EfCoreVogenConverters.StationIdEfCoreValueConverter(),
                valueComparer: new TradePath.DataStore.Database.EfCoreVogenConverters.StationIdEfCoreValueComparer());

            var match = runtimeEntityType.AddProperty(
                "Match",
                typeof(string),
                propertyInfo: typeof(NameFts<StationId, Station>).GetProperty("Match", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NameFts<StationId, Station>).GetField("<Match>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            match.AddAnnotation("Relational:ColumnName", "SystemNameIndex");

            var rank = runtimeEntityType.AddProperty(
                "Rank",
                typeof(double?),
                propertyInfo: typeof(NameFts<StationId, Station>).GetProperty("Rank", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NameFts<StationId, Station>).GetField("<Rank>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { entityId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("EntityId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var entity = declaringEntityType.AddNavigation("Entity",
                runtimeForeignKey,
                onDependent: true,
                typeof(Station),
                propertyInfo: typeof(NameFts<StationId, Station>).GetProperty("Entity", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(NameFts<StationId, Station>).GetField("<Entity>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "StationNameIndex");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
