// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using NetTopologySuite.Geometries;
using TradePath.Models;
using StarSystem = TradePath.Models.StarSystem;
using StarSystemId = TradePath.Models.StarSystemId;
using StarSystemName = TradePath.Models.StarSystemName;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TradePath.DataStore.Database.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class StarSystemEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "TradePath.Models.StarSystem",
                typeof(StarSystem),
                baseEntityType,
                propertyCount: 4,
                navigationCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(StarSystemId),
                propertyInfo: typeof(StarSystem).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(StarSystem).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueConverter: new TradePath.DataStore.Database.EfCoreVogenConverters.StarSystemIdEfCoreValueConverter(),
                valueComparer: new TradePath.DataStore.Database.EfCoreVogenConverters.StarSystemIdEfCoreValueComparer());

            var lastModified = runtimeEntityType.AddProperty(
                "LastModified",
                typeof(DateTimeOffset),
                propertyInfo: typeof(StarSystem).GetProperty("LastModified", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(StarSystem).GetField("<LastModified>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                concurrencyToken: true,
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            lastModified.AddAnnotation("Relational:DefaultValueSql", "CURRENT_TIMESTAMP");

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(StarSystemName),
                propertyInfo: typeof(StarSystem).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(StarSystem).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new TradePath.DataStore.Database.EfCoreVogenConverters.StarSystemNameEfCoreValueConverter(),
                valueComparer: new TradePath.DataStore.Database.EfCoreVogenConverters.StarSystemNameEfCoreValueComparer());

            var position = runtimeEntityType.AddProperty(
                "Position",
                typeof(Point),
                propertyInfo: typeof(StarSystem).GetProperty("Position", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(StarSystem).GetField("<Position>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            position.AddAnnotation("Relational:ColumnType", "POINTZ");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Systems");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
