// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using TradePath.Models;
using Star = TradePath.Models.Star;
using StarId = TradePath.Models.StarId;
using StarSystem = TradePath.Models.StarSystem;
using StarSystemId = TradePath.Models.StarSystemId;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TradePath.DataStore.Database.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class StarEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "TradePath.Models.Star",
                typeof(Star),
                baseEntityType,
                propertyCount: 5,
                navigationCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(StarId),
                propertyInfo: typeof(Star).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Star).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueConverter: new TradePath.DataStore.Database.EfCoreVogenConverters.StarIdEfCoreValueConverter(),
                valueComparer: new TradePath.DataStore.Database.EfCoreVogenConverters.StarIdEfCoreValueComparer());

            var canBoost = runtimeEntityType.AddProperty(
                "CanBoost",
                typeof(bool),
                propertyInfo: typeof(Star).GetProperty("CanBoost", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Star).GetField("<CanBoost>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var canScoop = runtimeEntityType.AddProperty(
                "CanScoop",
                typeof(bool),
                propertyInfo: typeof(Star).GetProperty("CanScoop", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Star).GetField("<CanScoop>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var distanceFromPrimary = runtimeEntityType.AddProperty(
                "DistanceFromPrimary",
                typeof(float?),
                propertyInfo: typeof(Star).GetProperty("DistanceFromPrimary", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Star).GetField("<DistanceFromPrimary>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var systemId = runtimeEntityType.AddProperty(
                "SystemId",
                typeof(StarSystemId),
                propertyInfo: typeof(Star).GetProperty("SystemId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Star).GetField("<SystemId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new TradePath.DataStore.Database.EfCoreVogenConverters.StarSystemIdEfCoreValueConverter(),
                valueComparer: new TradePath.DataStore.Database.EfCoreVogenConverters.StarSystemIdEfCoreValueComparer());

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { systemId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("SystemId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var system = declaringEntityType.AddNavigation("System",
                runtimeForeignKey,
                onDependent: true,
                typeof(StarSystem),
                propertyInfo: typeof(Star).GetProperty("System", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Star).GetField("<System>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var stars = principalEntityType.AddNavigation("Stars",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<Star>),
                propertyInfo: typeof(StarSystem).GetProperty("Stars", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(StarSystem).GetField("<Stars>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Star");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
