// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using TradePath.Models;
using TradePath.Models;
using StarSystem = TradePath.Models.StarSystem;
using StarSystemId = TradePath.Models.StarSystemId;
using Station = TradePath.Models.Station;
using StationId = TradePath.Models.StationId;
using StationName = TradePath.Models.StationName;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TradePath.DataStore.Database.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class StationEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "TradePath.Models.Station",
                typeof(Station),
                baseEntityType,
                propertyCount: 8,
                navigationCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(StationId),
                propertyInfo: typeof(Station).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Station).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueConverter: new TradePath.DataStore.Database.EfCoreVogenConverters.StationIdEfCoreValueConverter(),
                valueComparer: new TradePath.DataStore.Database.EfCoreVogenConverters.StationIdEfCoreValueComparer());

            var distanceFromPrimary = runtimeEntityType.AddProperty(
                "DistanceFromPrimary",
                typeof(float),
                propertyInfo: typeof(Station).GetProperty("DistanceFromPrimary", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Station).GetField("<DistanceFromPrimary>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0f);

            var isPermanent = runtimeEntityType.AddProperty(
                "IsPermanent",
                typeof(bool),
                propertyInfo: typeof(Station).GetProperty("IsPermanent", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Station).GetField("<IsPermanent>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var isPlanetary = runtimeEntityType.AddProperty(
                "IsPlanetary",
                typeof(bool),
                propertyInfo: typeof(Station).GetProperty("IsPlanetary", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Station).GetField("<IsPlanetary>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var isPlayerOwned = runtimeEntityType.AddProperty(
                "IsPlayerOwned",
                typeof(bool),
                propertyInfo: typeof(Station).GetProperty("IsPlayerOwned", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Station).GetField("<IsPlayerOwned>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var maxPadSize = runtimeEntityType.AddProperty(
                "MaxPadSize",
                typeof(PadSize),
                propertyInfo: typeof(Station).GetProperty("MaxPadSize", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Station).GetField("<MaxPadSize>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            maxPadSize.SetSentinelFromProviderValue((byte)0);

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(StationName),
                propertyInfo: typeof(Station).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Station).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new TradePath.DataStore.Database.EfCoreVogenConverters.StationNameEfCoreValueConverter(),
                valueComparer: new TradePath.DataStore.Database.EfCoreVogenConverters.StationNameEfCoreValueComparer());

            var systemId = runtimeEntityType.AddProperty(
                "SystemId",
                typeof(StarSystemId),
                propertyInfo: typeof(Station).GetProperty("SystemId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Station).GetField("<SystemId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new TradePath.DataStore.Database.EfCoreVogenConverters.StarSystemIdEfCoreValueConverter(),
                valueComparer: new TradePath.DataStore.Database.EfCoreVogenConverters.StarSystemIdEfCoreValueComparer());

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { systemId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("SystemId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var system = declaringEntityType.AddNavigation("System",
                runtimeForeignKey,
                onDependent: true,
                typeof(StarSystem),
                propertyInfo: typeof(Station).GetProperty("System", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Station).GetField("<System>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Stations");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
