// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using TradePath.DataStore.Database;
using TradePath.DataStore.Database;

#nullable disable

namespace TradePath.DataStore.Database.Migrations
{
    [DbContext(typeof(GalDataContext))]
    [Migration("20250429155229_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("TradePath.DataStore.Database.NameFts<TradePath.Models.StarSystemId, TradePath.Models.StarSystem>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Match")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rank")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("SystemNameIndex");
                });

            modelBuilder.Entity("TradePath.DataStore.Database.NameFts<TradePath.Models.StationId, TradePath.Models.Station>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Match")
                        .HasColumnType("TEXT")
                        .HasColumnName("SystemNameIndex");

                    b.Property<double?>("Rank")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("StationNameIndex");
                });

            modelBuilder.Entity("TradePath.Models.Star", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanBoost")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanScoop")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("DistanceFromPrimary")
                        .HasColumnType("REAL");

                    b.Property<int>("SystemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SystemId");

                    b.ToTable("Star");
                });

            modelBuilder.Entity("TradePath.Models.StarSystem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastModified")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Point>("Position")
                        .IsRequired()
                        .HasColumnType("POINTZ");

                    b.HasKey("Id");

                    b.ToTable("Systems");
                });

            modelBuilder.Entity("TradePath.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<float>("DistanceFromPrimary")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsPermanent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlanetary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlayerOwned")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MaxPadSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SystemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SystemId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("TradePath.DataStore.Database.NameFts<TradePath.Models.StarSystemId, TradePath.Models.StarSystem>", b =>
                {
                    b.HasOne("TradePath.Models.StarSystem", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("TradePath.DataStore.Database.NameFts<TradePath.Models.StationId, TradePath.Models.Station>", b =>
                {
                    b.HasOne("TradePath.Models.Station", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("TradePath.Models.Star", b =>
                {
                    b.HasOne("TradePath.Models.StarSystem", "System")
                        .WithMany("Stars")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("TradePath.Models.Station", b =>
                {
                    b.HasOne("TradePath.Models.StarSystem", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("TradePath.Models.StarSystem", b =>
                {
                    b.Navigation("Stars");
                });
#pragma warning restore 612, 618
        }
    }
}
