<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PublishAot>false</PublishAot>
		<InvariantGlobalization>true</InvariantGlobalization>
	</PropertyGroup>

	<PropertyGroup Condition="'$(UseSystemSqlite)' == ''">
		<UseSystemSqlite>false</UseSystemSqlite>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DeviceId"/>
		<PackageReference Include="DeviceId.Linux"/>
		<PackageReference Include="DeviceId.Mac"/>
		<PackageReference Include="DeviceId.Windows"/>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core"/>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite"/>
		<PackageReference Include="Microsoft.Extensions.Logging.Console"/>
		<PackageReference Include="Microsoft.Extensions.Logging.Debug"/>
		<PackageReference Include="OpenTelemetry"/>
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol"/>
		<PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Process" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
		<PackageReference Include="OpenTelemetry.Resources.Host" />
		<PackageReference Include="OpenTelemetry.Resources.OperatingSystem" />
		<PackageReference Include="OpenTelemetry.Resources.ProcessRuntime" />
		<PackageReference Include="Prise"/>
		<PackageReference Include="Spectre.Console"/>
		<PackageReference Include="System.CommandLine"/>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<Choose>
		<When Condition="'$(UseSystemSqlite)' == 'true'">
			<ItemGroup>
				<PackageReference Include="SQLitePCLRaw.bundle_sqlite3"/>
			</ItemGroup>
		</When>
		<Otherwise>
			<ItemGroup>
				<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3"/>
			</ItemGroup>
		</Otherwise>
	</Choose>

	<ItemGroup>
		<ProjectReference Include="..\..\data\DataStore\DataStore.csproj"/>
		<ProjectReference Include="..\..\data\Models\Models.csproj"/>
		<ProjectReference Include="..\..\plugin\Contracts\Contracts.csproj"/>
		<ProjectReference Include="..\..\plugin\HostHelpers\HostHelpers.csproj"/>
	</ItemGroup>

	<ItemGroup Condition="'$(_IsPublishing)' != 'yes'">
		<ProjectReference
			Include="..\..\plugin\Edsm\Edsm.csproj"
			ReferenceOutputAssembly="false"
			OutputItemType="PluginReference"
		/>
	</ItemGroup>

	<Target
		Name="ConfigurePluginFeeds"
		BeforeTargets="AssignTargetPaths"
		Inputs="@(PluginReference)"
		Outputs="$(IntermediateOutputPath)plugins.nuget.config"
	>
		<ItemGroup>
			<PluginFeedReference Include="@(PluginReference->'%(filename)')">
				<FeedUrl>@(PluginReference->'%(RelativeDir)..')</FeedUrl>
			</PluginFeedReference>
			<PluginFeedReference Include="nuget.org">
				<FeedUrl>https://api.nuget.org/v3/index.json</FeedUrl>
			</PluginFeedReference>
		</ItemGroup>

		<PropertyGroup>
			<PluginNuGetConfig>
				<![CDATA[<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<packageSources>
		<clear />
		@(PluginFeedReference->'<add key="%(Identity)" value="%(FeedUrl)" />')
	</packageSources>
	<config>
		<add key="dependencyVersion" value="HighestMinor" />
		<add key="globalPackagesFolder" value="./plugins/pkg" />
	</config>
</configuration>]]>
			</PluginNuGetConfig>
		</PropertyGroup>

		<WriteLinesToFile
			File="$(IntermediateOutputPath)plugins.nuget.config"
			Lines="$(PluginNuGetConfig)"
			Overwrite="true"
		/>

		<ItemGroup>
			<Content Include="$(IntermediateOutputPath)plugins.nuget.config">
				<CopyToOutputDirectory>Always</CopyToOutputDirectory>
				<Visible>false</Visible>
				<TargetPath>plugins/nuget.config</TargetPath>
			</Content>
			<FileWrites Include="$(IntermediateOutputPath)plugins.nuget.config"/>
		</ItemGroup>
	</Target>


	<ItemGroup>
		<EmbeddedResource Update="Resources\Commands.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Commands.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Commands.sv.resx">
			<DependentUpon>Commands.resx</DependentUpon>
		</EmbeddedResource>
		<None Remove="Resources\default.nuget.config"/>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources\Commands.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Commands.resx</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>
